
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

  resilience4j:
    ratelimiter:
      instances:
          basic:
            limit-for-period: 10
            limit-refresh-period: 1m
            timeout-duration: 10s

  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:default-key}
  cache-ttl: 10000

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer